### PR TITLE
Create testfile.txt

### PR DESCRIPTION
**Pull request by randomcat1234**
@gping-dev ping yahoo.com -L 5 --from "Spain"

### CODE REVIEW

**Comment by randomcat1234** [comment]
@gping-dev ping yahoo.com -L 5 --from "France"

**Comment by randomcat1234** [comment]
@gping-dev ping yahoo.com -L 5 --from "USA"

**Comment by randomcat1234** [comment]
@gping-dev http elmundo.es from London,Paris,Madrid --method head --full -L 8

**Comment by gping-dev** [comment]
Here are the results for `http elmundo.es from London,Paris,Madrid --method head --full -L 8`
>**EU, GB, London, ASN:60841, BerryByte Limited**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:14:49 GMT
Server: Varnish
X-Varnish: 936023364
Location: https://elmundo.es/
Content-Length: 0
Connection: close


```
>**EU, GB, London, ASN:48266, Catixs Ltd**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:14:49 GMT
Server: Varnish
X-Varnish: 935399779
Location: https://elmundo.es/
Content-Length: 0
Connection: close


```
>**EU, GB, London, ASN:42831, Rochut Group**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:14:49 GMT
Server: Varnish
X-Varnish: 915284760
Location: https://elmundo.es/
Content-Length: 0
Connection: close


```
>**EU, FR, Paris, ASN:199524, G-Core Labs SA**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:14:49 GMT
Server: Varnish
X-Varnish: 920367929
Location: https://elmundo.es/
Content-Length: 0
Connection: close


```
>**Full results available here: [https://www.jsdelivr.com/globalping?measurement=mbuNNUbBA7wuZdzP](https://www.jsdelivr.com/globalping?measurement=mbuNNUbBA7wuZdzP)**

**Comment by randomcat1234** [comment]
@gping-dev dns elmundo.es from London,Paris,Madrid -L 6

**Comment by gping-dev** [comment]
Here are the results for `dns elmundo.es from London,Paris,Madrid -L 6`
>**EU, GB, London, ASN:20473, The Constant Company, LLC**
```
; <<>> DiG 9.16.37-Debian <<>> -t A elmundo.es -p 53 -4 +timeout=3 +tries=2 +nocookie +nsid
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23708
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;elmundo.es.			IN	A

;; ANSWER SECTION:
elmundo.es.		300	IN	A	34.90.247.117

;; Query time: 3 msec
;; SERVER: 108.61.10.10#53(108.61.10.10)
;; WHEN: Thu Jul 13 09:16:50 UTC 2023
;; MSG SIZE  rcvd: 55
```
>**EU, GB, London, ASN:200636, August-internet**
```
; <<>> DiG 9.16.37-Debian <<>> -t A elmundo.es -p 53 -4 +timeout=3 +tries=2 +nocookie +nsid
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17746
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; NSID: 67 70 64 6e 73 2d 6c 68 72 ("gpdns-lhr")
;; QUESTION SECTION:
;elmundo.es.			IN	A

;; ANSWER SECTION:
elmundo.es.		270	IN	A	34.90.247.117

;; Query time: 12 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jul 13 09:17:48 UTC 2023
;; MSG SIZE  rcvd: 68
```
>**EU, FR, Paris, ASN:16509, Amazon.com (aws-eu-west-3)**
```
; <<>> DiG 9.16.27-Debian <<>> -t A elmundo.es -p 53 -4 +timeout=3 +tries=2 +nocookie +nsid
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10853
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;elmundo.es.			IN	A

;; ANSWER SECTION:
elmundo.es.		179	IN	A	34.90.247.117

;; Query time: 4 msec
;; SERVER: x.x.x.x#53(x.x.x.x)
;; WHEN: Thu Jul 13 09:16:50 UTC 2023
;; MSG SIZE  rcvd: 55
```
>**EU, FR, Paris, ASN:199524, G-Core Labs SA**
```
; <<>> DiG 9.16.37-Debian <<>> -t A elmundo.es -p 53 -4 +timeout=3 +tries=2 +nocookie +nsid
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23045
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;elmundo.es.			IN	A

;; ANSWER SECTION:
elmundo.es.		300	IN	A	34.90.247.117

;; Query time: 15 msec
;; SERVER: x.x.x.x#53(x.x.x.x)
;; WHEN: Thu Jul 13 09:16:50 UTC 2023
;; MSG SIZE  rcvd: 55
```
>**Full results available here: [https://www.jsdelivr.com/globalping?measurement=5KD5gf3CKOu96Qgh](https://www.jsdelivr.com/globalping?measurement=5KD5gf3CKOu96Qgh)**

**Comment by randomcat1234** [comment]
@gping-dev http elmundo.es from London,Paris,Madrid --method head --full -L 3

**Comment by gping-dev** [comment]
Here are the results for `http elmundo.es from London,Paris,Madrid --method head --full -L 3`
>**EU, GB, London, ASN:48266, Catixs Ltd**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:17:38 GMT
Server: Varnish
X-Varnish: 917087271
Location: https://elmundo.es/
Content-Length: 0
Connection: close
```
>**EU, FR, Paris, ASN:199524, G-Core Labs SA**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:17:38 GMT
Server: Varnish
X-Varnish: 920530350
Location: https://elmundo.es/
Content-Length: 0
Connection: close
```
>**EU, ES, Madrid, ASN:174, Cogent Communications**
```
HTTP/1.1 301
Date: Thu, 13 Jul 2023 09:17:38 GMT
Server: Varnish
X-Varnish: 924389842
Location: https://elmundo.es/
Content-Length: 0
Connection: close
```

**Comment by randomcat1234** [comment]
@gping-dev mtr -L 3 --share

**Comment by gping-dev** [comment]
Failed to process command `mtr -L 3 --share`.
```
Validation Failed
"target" is required
```
Documentation and Support: https://github.com/jsdelivr/globalping

**Comment by randomcat1234** [comment]
@gping-dev nytimes.com mtr -L 3 --share

**Comment by randomcat1234** [comment]
@gping-dev nytimes.com mtr -L 3 --share

**Comment by gping-dev** [comment]
Failed to process command `nytimes.com mtr -L 3 --share`.
```
Invalid argument "nytimes.com" for "command"!
Expected "ping, traceroute, dns, mtr, http".
```
Documentation and Support: https://github.com/jsdelivr/globalping

**Comment by randomcat1234** [comment]
@gping-dev mtr nytimes.com -L 3 --share

**Comment by gping-dev** [comment]
Here are the results for `mtr nytimes.com -L 3 --share`
>**EU, PL, Warsaw, ASN:16276, OVH SAS**
```
Host                                                        Loss% Drop Rcv   Avg  StDev  Javg 
 1. AS16276 _gateway (146.59.47.252)                         0.0%    0   3   0.6    0.1   0.4
 2. AS???   10.162.35.2 (10.162.35.2)                        0.0%    0   3   0.7    0.0   0.3
 3. AS???   10.17.228.76 (10.17.228.76)                      0.0%    0   3   0.9    0.3   0.7
 4. AS???   10.73.24.150 (10.73.24.150)                      0.0%    0   3   0.7    0.4   0.7
 5. AS???   10.73.248.194 (10.73.248.194)                    0.0%    0   3 733.7  260.5 732.7
 6. AS16276 be101.waw-atm-sbb1-nc5.pl.eu (213.186.32.202)    0.0%    0   3   1.7    0.3   1.1
 7. AS16276 fra-fr5-sbb2-nc5.de.eu (54.36.50.116)            0.0%    0   3  21.6    0.1  10.9
 8. AS???   10.200.0.19 (10.200.0.19)                        0.0%    0   3  19.2    0.9  10.2
 9. AS???   fra1.decixfra.fastly.net (80.81.195.54)          0.0%    0   3  21.7    0.2  11.0
10. AS54113 151.101.1.164 (151.101.1.164)                    0.0%    0   3  21.1    3.0  12.7
```
>**NA, US, (VA), Ashburn, ASN:213230, Hetzner Online GmbH**
```
Host                                                                     Loss% Drop Rcv  Avg  StDev  Javg 
 1. AS???    _gateway (172.31.1.1)                                        0.0%    0   3  2.0    0.5   1.4
 2. AS213230 17916.your-cloud.host (5.161.8.176)                          0.0%    0   3  0.2    0.1   0.2
 3. AS???    (waiting for reply)                                       
 4. AS213230 spine2.cloud1.ash.hetzner.com (5.161.0.181)                  0.0%    0   3  0.9    0.2   0.6
 5. AS213230 core1.ash.hetzner.com (5.161.0.77)                           0.0%    0   3  1.8    0.6   0.7
 6. AS2914   ce-4-1-3.a04.asbnva02.us.bb.gin.ntt.net (128.241.9.94)       0.0%    0   3  2.7    0.7   2.3
 7. AS2914   ae-3.r24.asbnva02.us.bb.gin.ntt.net (129.250.2.144)          0.0%    0   3  1.4    0.4   1.2
 8. AS2914   ae-3.r23.chcgil09.us.bb.gin.ntt.net (129.250.2.139)          0.0%    0   3 25.1    6.3  19.4
 9. AS2914   ae-1.a05.chcgil09.us.bb.gin.ntt.net (129.250.4.238)          0.0%    0   3 16.0    0.0   8.0
10. AS2914   ae-3.fastly.chcgil09.us.bb.gin.ntt.net (128.241.14.66)       0.0%    0   3 18.0    0.1   9.1
11. AS54113  151.101.193.164 (151.101.193.164)                            0.0%    0   3 21.2    0.1  10.7
```
>**NA, US, (NC), Charlotte, ASN:7018, AT&T Internet**
```
Host                                                                       Loss% Drop Rcv Avg  StDev  Javg 
1. AS???   _gateway (10.0.0.1)                                              0.0%    0   3 0.4    0.1   0.3
2. AS???   dsldevice.attlocal.net (192.168.1.254)                           0.0%    0   3 0.9    0.2   0.6
3. AS7018  108-78-212-1.lightspeed.chrlnc.sbcglobal.net (108.78.212.1)      0.0%    0   3 1.8    0.1   1.0
4. AS7018  99.144.25.84 (99.144.25.84)                                      0.0%    0   3 1.9    0.1   1.0
5. AS???   (waiting for reply)                                           
6. AS7018  32.130.17.15 (32.130.17.15)                                      0.0%    0   3 7.2    0.2   3.5
7. AS???   (waiting for reply)                                           
8. AS54113 151.101.65.164 (151.101.65.164)                                  0.0%    0   3 7.3    0.1   3.6
```
>**View the results online: [https://www.jsdelivr.com/globalping?measurement=2pOox4HkMWsaVnvX](https://www.jsdelivr.com/globalping?measurement=2pOox4HkMWsaVnvX)**

**Comment by randomcat1234** [comment]
@gping-dev traceroute nytimes.com -L 2 --from USA

**Comment by gping-dev** [comment]
Here are the results for `traceroute nytimes.com -L 2 --from USA`
>**NA, US, (GA), Atlanta, ASN:62005, BlueVPS OU**
```
traceroute to nytimes.com (151.101.1.164), 20 hops max, 60 byte packets
 1  45.66.248.1 (45.66.248.1)  0.467 ms  0.426 ms
 2  lag-127.ear1.Atlanta2.Level3.net (4.36.12.29)  0.504 ms  0.404 ms
 3  FASTLY-INC.ear1.Atlanta2.Level3.net (4.14.93.194)  0.460 ms  0.421 ms
 4  151.101.1.164 (151.101.1.164)  1.026 ms  0.861 ms
```
>**NA, US, (CA), San Jose, ASN:16509, Amazon.com (aws-us-west-1)**
```
traceroute to nytimes.com (151.101.1.164), 20 hops max, 60 byte packets
 1  216.182.237.195 (216.182.237.195)  0.987 ms  0.974 ms
 2  * *
 3  * *
 4  * *
 5  241.0.6.194 (241.0.6.194)  0.223 ms  0.276 ms
 6  240.0.180.2 (240.0.180.2)  0.225 ms  0.222 ms
 7  242.2.51.165 (242.2.51.165)  0.922 ms  0.919 ms
 8  240.0.168.14 (240.0.168.14)  0.896 ms  0.965 ms
 9  242.2.26.199 (242.2.26.199)  1.121 ms  1.118 ms
10  15.230.28.70 (15.230.28.70)  0.824 ms  0.853 ms
11  * *
12  151.101.1.164 (151.101.1.164)  0.938 ms  0.935 ms
```

**Comment by randomcat1234** [comment]
@gping-dev traceroute help

**Comment by gping-dev** [comment]
traceroute tracks the route packets take from an IP network on their way to a given host.

**Examples:**
Traceroute google.com from 2 probes in New York
```
traceroute google.com from New York --limit 2
```
Traceroute 1.1.1.1 from 2 probes from USA or Belgium
```
traceroute 1.1.1.1 from USA,Belgium --limit 2
```
Traceroute jsdelivr.com from a probe that is from the AWS network and is located in Montreal using the UDP protocol
```
traceroute jsdelivr.com from aws+montreal --protocol udp
```
Traceroute jsdelivr.com from a probe that is located in Paris to port 453
```
traceroute jsdelivr.com from Paris --port 453
```

**Usage:**
```
@gping-dev traceroute [target] from [location] [flags]
```

**Flags**:
```
  -h, --help              Help for traceroute
      --port int          Specifies the port to use for the traceroute. Only applicable for TCP protocol (default 80)
      --protocol string   Specifies the protocol used for tracerouting (ICMP, TCP or UDP) (default "icmp")
```

**Global Flags**:
```
  -F, --from string       Comma-separated list of location values to match against. For example the partial or full name of a continent, region (e.g eastern europe), country, US state, city or network (default "world"). (default "world")
      --latency           Output only the stats of a measurement (default false). Only applies to the dns, http and ping commands
  -L, --limit int         Limit the number of probes to use (default 1)
      --share             Prints a link at the end the results, allowing to vizualize the results online (default false)
```

**Comment by randomcat1234** [comment]
@gping-dev help

**Comment by gping-dev** [comment]
Globalping is a platform that allows anyone to run networking commands such as ping, traceroute, dig and mtr on probes distributed all around the world.
The Globalping bot allows you to interact with the API in a simple and human-friendly way to debug networking issues like anycast routing and script automated tests and benchmarks.

**Usage:**
```
@gping-dev [command]
```

**Measurement Commands**:
```
  dns           Resolve a DNS record similarly to dig
  http          Perform a HEAD or GET request to a host
  mtr           Run an MTR test, similar to traceroute
  ping          Run a ping test
  traceroute    Run a traceroute test
```

**Additional Commands**:
```
  help          Help about any command
```

**Flags**:
```
  -F, --from string   Comma-separated list of location values to match against. For example the partial or full name of a continent, region (e.g eastern europe), country, US state, city or network (default "world"). (default "world")
  -h, --help          help for globalping
      --latency       Output only the stats of a measurement (default false). Only applies to the dns, http and ping commands
  -L, --limit int     Limit the number of probes to use (default 1)
      --share         Prints a link at the end the results, allowing to vizualize the results online (default false)

  Use "globalping [command] --help" for more information about a command.
```

**Pull request closed without merging**
